#! /bin/sh
# /etc/init.d/databaseEntries
# https://www.debian-administration.org/article/28/Making_scripts_run_at_boot_time_with_Debian
# http://raspberrypi.stackexchange.com/questions/13358/insserv-warning-script-mathkernel-missing-lsb-tags-and-overrides 

### BEGIN INIT INFO
# Provides:          databaseEntries
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to invoke /opt/databaseEntries
# Description:       Calls /opt/database entries which replaces yesterdays events backup
#                    with one that has valid data
### END INIT INFO

# Author: John O Riordan <joriordan@alienvault.com>
#

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt
DESC="Replacing yesterdays event backup with valid one"
NAME=databaseEntries
DAEMON=/opt/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# Some thing that always runs
# python /opt/databaseEntries/databaseEntries.py /opt/databaseEntries/insert-20150824.sql.gz

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting database replacement"
    python /opt/databaseEntries/databaseEntries.py /opt/databaseEntries/insert-20150824.sql.gz 2015-08-24 &>>/var/log/databaseEntries
    echo "Completed replacement script. Please review /var/log/databaseEntries"
    ;;
  stop)
    echo "Nothing to do."
    ;;
  *)
    exit 1
    ;;
esac

exit 0
